# render.yaml

services:
  - type: web
    name: django-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    # <-- fix: point at your Django project’s WSGI entrypoint, bind to $PORT -->
    startCommand: gunicorn TravelTogether.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "<your-production-secret-key>"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "django-web.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: travel-db
          property: connectionString

databases:
  - name: travel-db
    engine: postgresql
    plan: free
