# render.yaml

services:
  - type: web
    name: travel-together
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate

    startCommand: gunicorn TravelTogether.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
   