# Generated by Django 4.2.2 on 2023-06-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Product_Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
