# Generated by Django 4.2.2 on 2023-06-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_App', '0002_userdetails_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Product_Image',
            new_name='Image',
        ),
    ]
