# Generated by Django 4.2.2 on 2023-06-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_App', '0003_rename_product_image_userdetails_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=None, max_length=100, null=True)),
                ('Name', models.CharField(default=None, max_length=100, null=True)),
                ('Description', models.CharField(default=None, max_length=100, null=True)),
                ('Status', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
    ]
