# Generated by Django 4.2.2 on 2023-06-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_App', '0004_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='Image',
            field=models.ImageField(null=True, upload_to='GroupImages/'),
        ),
    ]
