# Generated by Django 4.2.2 on 2023-06-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_App', '0005_groups_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_App.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_App.userdetails')),
            ],
            options={
                'db_table': 'JoinRequests',
            },
        ),
    ]
