# Generated by Django 4.2.2 on 2023-06-12 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_App', '0007_alter_joinrequest_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_App.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_App.userdetails')),
            ],
            options={
                'db_table': 'Member',
            },
        ),
    ]
